AWSTemplateFormatVersion: '2010-09-09'
Description: 'Plantilla para crear instancia ec2'
Resources:
  AplicationServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Grupo de seguridad para el puerto 8080
      GroupName: AppServerSecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
  
  InstanciaEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c7217cdde317cfec
      InstanceType: t2.micro
      KeyName: vockey
      SecurityGroups:
        - Ref: AplicationServerSecurityGroup
      Tags: 
        - Key: Name
          Value: TemplateEC2

